pb_json - clear compilation error with protobuf 3.15
Protobuf version 3.15 caused the following error in gcc 10.2 when
compiling include/pwdb/pb_json.h:
"error: no matching function for call to
	std::runtime_error::runtime_error(google::protobuf::StringPiece)"